language: "ko-KR"

reviews:
  profile: "chill" 
  request_changes_workflow: false 
  high_level_summary: true 
  poem: false 
  
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
      - "[Draft]"

  tools:
    ast_grep:
      enabled: true
    github_checks:
      enabled: true

chat:
  auto_reply: true 

filter:
  changed_files:
    - "!dist/**"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!**/*.spec.ts" 
    - "!coverage/**"