# This is file of the project INGONG
# Licensed under the MIT License.
# Copyright (c) 2025 INGONG
# For full license text, see the LICENSE file in the root directory or at
# https://opensource.org/license/mit
# Author: junho Kim
# Latest Updated Date: 2025-07-24

apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  type: LoadBalancer  
  selector:
    app: nest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
