name: "🔧 Enhancement Request"
description: "기존 기능을 개선하는 제안"
labels: ["enhancement"]
assignees:
  - ""

body:
  - type: textarea
    attributes:
      label: ✨ 개선할 기능
      description: |
        - 개선이 필요한 기존 기능을 설명해주세요.
        - 현재의 문제점과 개선 후 기대되는 변화는 무엇인가요?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ✅ 구현 아이디어
      description: |
        - 개선을 위한 아이디어가 있다면 제안해주세요.
        - 예) "UI 버튼 색상을 변경하면 접근성이 향상됩니다."
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📌 추가 정보
      description: |
        - 관련 참고 자료나 추가 정보가 있다면 여기에 적어주세요.