name: "🚀 Feature Request: [기능 요약]"
description: "새로운 기능 추가 요청"
labels: ["feature", "enhancement"]
assignees:
  - ""

body:
  - type: textarea
    attributes:
      label: 📄 기능 설명
      description: |
        - 이 기능이 필요한 이유를 설명해주세요.
        - 현재 어떤 문제를 해결하기 위한 기능인가요?
        - 관련된 기존 기능이 있다면 함께 적어주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 구현 방안
      description: |
        - 이 기능을 어떻게 구현할 계획인가요?
        - 필요한 API, UI 변경 사항, 데이터 모델 수정 등을 단계적으로 설명해주세요.
        - 예) "1. 새로운 API 엔드포인트 추가, 2. UI 변경, 3. DB 모델 업데이트"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔗 관련 자료 (선택)
      description: |
        - 참고할 수 있는 문서, 디자인 파일, 관련 이슈 링크 등을 첨부해주세요.
        - 예) "Figma 디자인 링크", "이전에 논의된 관련 이슈"

  - type: textarea
    attributes:
      label: 🙋🏻 추가 정보
      description: |
        - 추가적으로 공유할 내용이 있다면 자유롭게 작성해주세요.
        - 예) "이 기능과 관련하여 특정 팀원의 검토가 필요합니다."
    validations:
      required: false