name: "💬 Question / Discussion"
description: "프로젝트와 관련된 질문 또는 토론"
labels: ["question"]
assignees:
  - ""

body:
  - type: textarea
    attributes:
      label: ❓ 질문 / 논의 내용
      description: |
        - 질문하고 싶은 내용을 구체적으로 적어주세요.
        - 논의할 주제라면 맥락을 설명해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📚 참고 자료 (선택)
      description: |
        - 관련 문서나 자료가 있다면 추가해주세요.

  - type: textarea
    attributes:
      label: 🙋 추가 의견
      description: |
        - 논의하고 싶은 추가 사항이 있다면 여기에 적어주세요.